# Generated by Django 4.2.8 on 2023-12-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sala_konferencyjna', '0002_hall_capacity_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='availability_hall',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='availability_of_projector',
            field=models.BooleanField(),
        ),
    ]
